include:
  project: "grp-arch/sp-push"
  ref: main
  file:
    - argocd-nodejs-ci-new-bak.yml
build:
  stage: build
  #image: "nexus.gp51.com/library/node:18-alpine"
  script: |
    rm -rf dist
    nvm use 20
    npm install -g yarn
    yarn config set registry https://registry.npmmirror.com
    yarn install
    yarn global add vite@latest
    if [ -n  "${CI_COMMIT_TAG}" ];then
      yarn build
    elif [ "$CI_COMMIT_REF_NAME" == "test" ];then
      yarn build --mode staging
    elif [ "$CI_COMMIT_REF_NAME" == "uat" ]; then
      yarn build --mode staging
    fi
  artifacts:
    paths:
      - dist
    expire_in: 20 minutes
  tags:
    - host
  only:
    - test
    - uat
    - tags
