/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataSource: typeof import('./src/components/DataSource.vue')['default']
    QueryConfigComp: typeof import('./src/components/QueryConfigComp.vue')['default']
    QueryConfigSign: typeof import('./src/components/QueryConfigSign.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastInfo: typeof import('./src/components/ToastInfo.vue')['default']
  }
}
