/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./src/components/snack-bar.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    ToastInfo: typeof import('./src/components/ToastInfo.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
